const num1 = 20;
const num3 = 30;

console.log(num1);

// intenta hacer lo siguiente
try {
  console.log(num2);
} catch (error) {
  console.log(error);
}
// En caso de que no exista, el código se seguíra ejecutando

console.log(num3);
